# Generated by Django 5.1.15 on 2026-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('client', models.CharField(max_length=200)),
                ('client_fr', models.CharField(max_length=200, null=True)),
                ('client_en', models.CharField(max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('industry_fr', models.CharField(blank=True, max_length=120, null=True)),
                ('industry_en', models.CharField(blank=True, max_length=120, null=True)),
                ('challenge', models.TextField()),
                ('challenge_fr', models.TextField(null=True)),
                ('challenge_en', models.TextField(null=True)),
                ('solution', models.TextField()),
                ('solution_fr', models.TextField(null=True)),
                ('solution_en', models.TextField(null=True)),
                ('results', models.TextField()),
                ('results_fr', models.TextField(null=True)),
                ('results_en', models.TextField(null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie')], default='published', max_length=20)),
                ('published_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'case studies',
                'ordering': ['-published_at'],
            },
        ),
    ]
