# Generated by Django 5.1.15 on 2026-04-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='meta_description',
            field=models.TextField(blank=True, help_text="155-160 chars, used for <meta name='description'>", max_length=300),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text="155-160 chars, used for <meta name='description'>", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='meta_description_fr',
            field=models.TextField(blank=True, help_text="155-160 chars, used for <meta name='description'>", max_length=300, null=True),
        ),
    ]
