# Generated by Django 5.1.15 on 2026-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('locasur', 'LocaSur'), ('postflow', 'postFlow'), ('generic', 'Generic')], default='generic', max_length=30)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacte'), ('qualified', 'Qualifie'), ('lost', 'Perdu')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
